name: "Free Disk Space (Ubuntu)"
description: "A configurable GitHub Action to free up disk space on an Ubuntu GitHub Actions runner."

branding:
  icon: "trash-2"
  color: "green"

inputs:
  android:
    description: "Remove Android runtime"
    required: false
    default: "true"
  dotnet:
    description: "Remove .NET runtime"
    required: false
    default: "true"
  haskell:
    description: "Remove Haskell runtime"
    required: false
    default: "true"
  large-packages:
    description: "Remove large packages"
    required: false
    default: "true"
  docker-images:
    description: "Remove Docker images"
    required: false
    default: "true"
  tool-cache:
    description: "Remove image tool cache"
    required: false
    default: "false"
  swap-storage:
    description: "Remove swap storage"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Make script executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/free_space.sh

    - name: Run free disk space script
      shell: bash
      run: ${{ github.action_path }}/free_space.sh
      env:
        INPUT_ANDROID: ${{ inputs.android }}
        INPUT_DOTNET: ${{ inputs.dotnet }}
        INPUT_HASKELL: ${{ inputs.haskell }}
        INPUT_LARGE_PACKAGES: ${{ inputs.large-packages }}
        INPUT_DOCKER_IMAGES: ${{ inputs.docker-images }}
        INPUT_TOOL_CACHE: ${{ inputs.tool-cache }}
        INPUT_SWAP_STORAGE: ${{ inputs.swap-storage }}
